-- Seed: catálogo de táticas de golpe (scam_patterns)
insert into public.scam_patterns (id, label, description, severity, category, keywords) values
  ('urgencia_artificial', 'Urgência artificial', 'Criam senso de urgência para impedir que você pense com calma ou confirme com outra pessoa.', 'alto', 'pressao_psicologica', ARRAY['urgente', 'imediatamente', 'agora mesmo', 'últimos minutos', 'expira hoje', 'até às \d', 'em \d+ minutos']::text[]),
  ('ameaca', 'Ameaça', 'Uso de ameaças (bloqueio, multa, prisão, corte de serviço) para gerar medo.', 'alto', 'pressao_psicologica', ARRAY['será bloquead', 'conta será encerrada', 'você será preso', 'ação judicial', 'processo criminal', 'multa de', 'suspens[ãa]o']::text[]),
  ('medo', 'Indução de medo', 'Mensagem construída para provocar pânico e reduzir a capacidade de análise crítica.', 'medio', 'pressao_psicologica', ARRAY['não conte para ningu[ée]m', 'não desligue', 'não fale com ningu[ée]m', 'segredo', 'perigo']::text[]),
  ('promessa_dinheiro', 'Promessa de dinheiro fácil', 'Oferece dinheiro, prêmio ou retorno financeiro incomum.', 'alto', 'pressao_psicologica', ARRAY['voc[êe] ganhou', 'pr[êe]mio', 'sorteio', 'dinheiro fácil', 'renda extra garantida', 'retorno de \d+%']::text[]),
  ('premio_inesperado', 'Prêmio inesperado', 'Comunicação não solicitada informando um prêmio ou benefício surpresa.', 'alto', 'pressao_psicologica', ARRAY['foi sorteado', 'contemplado', 'brinde exclusivo', 'presente surpresa']::text[]),
  ('pedido_pix', 'Pedido de Pix', 'Solicitação de transferência via Pix, frequentemente para uma chave que não pertence à instituição oficial.', 'alto', 'pedido_de_dados_ou_dinheiro', ARRAY['fa[çc]a um pix', 'transfira via pix', 'chave pix', 'pix para essa chave']::text[]),
  ('pedido_codigo_sms', 'Pedido de código de SMS/autenticação', 'Pedido do código de verificação recebido por SMS, e-mail ou aplicativo. Nenhuma empresa séria pede esse código.', 'alto', 'pedido_de_dados_ou_dinheiro', ARRAY['código que chegou', 'código de verifica[çc][ãa]o', 'me (envia|passa|manda) o código', 'código do sms']::text[]),
  ('pedido_senha', 'Pedido de senha', 'Solicitação de senha de aplicativos, e-mail ou bancos.', 'alto', 'pedido_de_dados_ou_dinheiro', ARRAY['me (envia|passa|manda) (a |sua )?senha', 'informe sua senha', 'confirme sua senha']::text[]),
  ('pedido_dados_bancarios', 'Pedido de dados bancários', 'Solicitação de número de conta, agência, cartão ou dados de acesso bancário.', 'alto', 'pedido_de_dados_ou_dinheiro', ARRAY['n[úu]mero do cart[ãa]o', 'dados banc[áa]rios', 'agência e conta', 'cvv']::text[]),
  ('pedido_dados_pessoais', 'Pedido de dados pessoais sensíveis', 'Solicitação de CPF, RG, data de nascimento ou outros dados pessoais fora de um canal oficial.', 'medio', 'pedido_de_dados_ou_dinheiro', ARRAY['me (envia|passa|manda) (seu |o )?cpf', 'n[úu]mero do rg', 'confirme seus dados']::text[]),
  ('cobranca_inesperada', 'Cobrança inesperada', 'Cobrança de um valor que a pessoa não reconhece ou não esperava.', 'medio', 'pedido_de_dados_ou_dinheiro', ARRAY['cobran[çc]a n[ãa]o reconhecida', 'fatura em aberto', 'd[ée]bito pendente']::text[]),
  ('falso_reembolso', 'Falso reembolso', 'Oferta de reembolso ou estorno que exige dados ou pagamento antecipado.', 'alto', 'pedido_de_dados_ou_dinheiro', ARRAY['reembolso dispon[íi]vel', 'estorno pendente', 'devolu[çc][ãa]o de valor']::text[]),
  ('qr_code_suspeito', 'QR Code suspeito', 'Envio de QR Code para pagamento ou acesso fora de canais oficiais.', 'medio', 'pedido_de_dados_ou_dinheiro', ARRAY['escaneie o qr ?code', 'leia o qr ?code', 'aponte a câmera']::text[]),
  ('falso_funcionario_banco', 'Possível falso funcionário de banco', 'A pessoa se identifica como funcionário de um banco através de um canal não oficial.', 'alto', 'identidade_falsa', ARRAY['sou (do|da) (banco|caixa|ita[uú]|bradesco|santander|nubank)', 'gerente da sua conta', 'central de seguran[çc]a do banco']::text[]),
  ('falso_funcionario_governo', 'Possível falso funcionário público', 'A pessoa alega representar um órgão do governo.', 'alto', 'identidade_falsa', ARRAY['receita federal', 'inss', 'minist[ée]rio', 'governo federal']::text[]),
  ('falso_policial', 'Possível falso policial', 'A pessoa alega ser policial ou agente de autoridade.', 'alto', 'identidade_falsa', ARRAY['sou (da )?pol[íi]cia', 'delegacia', 'sou policial']::text[]),
  ('falso_advogado', 'Possível falso advogado', 'A pessoa alega ser advogado, geralmente em contexto de um familiar em apuros.', 'medio', 'identidade_falsa', ARRAY['sou (o |a )?advogad', 'represento juridicamente']::text[]),
  ('falso_familiar', 'Possível falso familiar (golpe do parente)', 'Mensagem alegando ser um filho, neto ou parente em dificuldade, geralmente pedindo dinheiro com urgência.', 'alto', 'identidade_falsa', ARRAY['é a mãe', 'é o pai', 'aqui é seu filho', 'perdi meu celular', 'esse é meu novo n[úu]mero']::text[]),
  ('falso_entregador', 'Possível falso entregador/transportadora', 'Mensagem alegando problema em uma entrega, com link para "reagendar" ou "pagar taxa".', 'medio', 'identidade_falsa', ARRAY['sua encomenda', 'objeto retido', 'taxa de reenvio', 'tentativa de entrega']::text[]),
  ('falso_suporte_tecnico', 'Possível falso suporte técnico', 'Contato alegando ser suporte técnico, pedindo acesso remoto ou instalação de aplicativo.', 'alto', 'identidade_falsa', ARRAY['suporte t[ée]cnico', 'acesso remoto', 'instale este aplicativo', 'anydesk', 'teamviewer']::text[]),
  ('falso_emprego', 'Possível falsa oferta de emprego', 'Oferta de emprego com pagamento antecipado, tarefas simples e retorno alto.', 'alto', 'identidade_falsa', ARRAY['vaga de emprego', 'trabalhe de casa', 'renda extra', 'tarefa di[áa]ria']::text[]),
  ('canal_nao_oficial', 'Contato por canal não oficial', 'O primeiro contato aconteceu por um canal que a instituição normalmente não usa (WhatsApp pessoal, por exemplo).', 'medio', 'canal_e_link', ARRAY['pelo whatsapp', 'me chamou no whatsapp', 'n[úu]mero pessoal']::text[]),
  ('link_suspeito', 'Link suspeito', 'Um link foi enviado pedindo para clicar e inserir dados.', 'alto', 'canal_e_link', ARRAY['clique (aqui|no link)', 'acesse o link', 'http[s]?://']::text[]),
  ('dominio_parecido', 'Domínio parecido com empresa legítima', 'O link usa um domínio semelhante, mas não idêntico, ao domínio oficial da empresa citada.', 'alto', 'canal_e_link', ARRAY['\.com-', '\.net-', '-oficial\.', '\.info\b', '\.xyz\b']::text[]),
  ('boleto_falso', 'Possível boleto falso', 'Boleto enviado fora do canal oficial de cobrança, com dados divergentes.', 'alto', 'canal_e_link', ARRAY['boleto em anexo', 'segunda via do boleto', 'boleto atualizado']::text[]),
  ('investimento_fraudulento', 'Possível investimento fraudulento', 'Promessa de retorno financeiro alto, rápido e "garantido" — incompatível com investimentos reais.', 'alto', 'financeiro', ARRAY['retorno garantido', 'lucro garantido', 'sem risco', '\d+% ao (m[êe]s|dia)']::text[]),
  ('piramide_financeira', 'Possível pirâmide financeira', 'Modelo que depende de recrutar novos participantes para gerar retorno.', 'alto', 'financeiro', ARRAY['indique (amigos|pessoas) e ganhe', 'sistema de indica[çc][ãa]o', 'multin[íi]vel']::text[]),
  ('falso_emprestimo', 'Possível falso empréstimo', 'Oferta de empréstimo com taxa antecipada obrigatória, prática ilegal no Brasil.', 'alto', 'financeiro', ARRAY['empr[ée]stimo aprovado', 'libera[çc][ãa]o mediante taxa', 'pague uma taxa para liberar']::text[]),
  ('falso_financiamento', 'Possível falso financiamento', 'Oferta de financiamento com condições incomuns e pedido de pagamento antecipado.', 'medio', 'financeiro', ARRAY['financiamento pr[ée]-aprovado', 'crédito facilitado']::text[]),
  ('falso_beneficio', 'Possível falso benefício governamental', 'Comunicação sobre um benefício do governo (auxílio, restituição) fora dos canais oficiais.', 'alto', 'financeiro', ARRAY['aux[íi]lio dispon[íi]vel', 'benef[íi]cio liberado', 'restitui[çc][ãa]o do imposto de renda']::text[]),
  ('golpe_marketplace', 'Golpe de marketplace/compra e venda', 'Negociação de compra/venda com pedido de pagamento fora da plataforma oficial.', 'alto', 'contexto_especifico', ARRAY['pagamento fora do site', 'combinamos fora do (site|app)', 'chave pix diferente']::text[]),
  ('golpe_aluguel', 'Golpe de aluguel', 'Anúncio de aluguel com preço muito abaixo do mercado, exigindo pagamento adiantado sem visita.', 'alto', 'contexto_especifico', ARRAY['alugo sem fiador', 'chave mediante dep[óo]sito', 'n[ãa]o precisa visitar']::text[]),
  ('golpe_afetivo', 'Possível golpe do romance', 'Relacionamento à distância que evolui para pedidos de dinheiro.', 'alto', 'contexto_especifico', ARRAY['preciso de dinheiro para (te visitar|a passagem)', 'estou preso na alf[âa]ndega', 'perdi meus documentos no exterior']::text[]),
  ('clonagem_conta', 'Sinal de clonagem/roubo de conta', 'Indícios de que uma conta (WhatsApp, redes sociais) foi clonada ou tomada por terceiros.', 'alto', 'contexto_especifico', ARRAY['minha conta foi clonada', 'perdi acesso [àa] minha conta', 'n[ãa]o consigo entrar no whatsapp']::text[]),
  ('falso_sequestro', 'Possível falso sequestro', 'Ligação alegando sequestro ou acidente de um familiar, exigindo pagamento imediato.', 'alto', 'contexto_especifico', ARRAY['sofreu um acidente', 'foi sequestrad', 'est[áa] em meu poder']::text[]),
  ('extorsao_sextorsao', 'Possível extorsão/sextorsão', 'Ameaça de divulgar imagens ou informações comprometedoras caso não haja pagamento.', 'alto', 'contexto_especifico', ARRAY['vou divulgar suas fotos', 'vazar suas fotos', 'print da sua conversa']::text[])
on conflict (id) do update set label = excluded.label, description = excluded.description, severity = excluded.severity, category = excluded.category, keywords = excluded.keywords, updated_at = now();

-- Seed: domínios oficiais de referência (known_domains)
insert into public.known_domains (domain, category) values
  ('itau.com.br', 'bancos'),
  ('bradesco.com.br', 'bancos'),
  ('santander.com.br', 'bancos'),
  ('caixa.gov.br', 'bancos'),
  ('bb.com.br', 'bancos'),
  ('nubank.com.br', 'bancos'),
  ('inter.co', 'bancos'),
  ('c6bank.com.br', 'bancos'),
  ('picpay.com', 'bancos'),
  ('gov.br', 'governo'),
  ('inss.gov.br', 'governo'),
  ('receita.fazenda.gov.br', 'governo'),
  ('anvisa.gov.br', 'governo'),
  ('mercadolivre.com.br', 'marketplaces'),
  ('mercadopago.com.br', 'marketplaces'),
  ('amazon.com.br', 'marketplaces'),
  ('shopee.com.br', 'marketplaces'),
  ('magazineluiza.com.br', 'marketplaces'),
  ('americanas.com.br', 'marketplaces'),
  ('olx.com.br', 'marketplaces'),
  ('correios.com.br', 'transportadoras'),
  ('jadlog.com.br', 'transportadoras'),
  ('totalexpress.com.br', 'transportadoras'),
  ('whatsapp.com', 'redes_sociais'),
  ('instagram.com', 'redes_sociais'),
  ('facebook.com', 'redes_sociais'),
  ('telegram.org', 'redes_sociais')
on conflict (domain) do update set category = excluded.category;
